// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU7Iki76J2BWOMj434raRkJVlvYIoLtWU',
    appId: '1:792020357769:android:41916544a9b72397f32c58',
    messagingSenderId: '792020357769',
    projectId: 'frush-29e51',
    databaseURL: 'https://frush-29e51-default-rtdb.firebaseio.com',
    storageBucket: 'frush-29e51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGy7LmDFp_cUTAqW7Cf8EfmLyfdpOnqe8',
    appId: '1:792020357769:ios:099dffe241eee9b1f32c58',
    messagingSenderId: '792020357769',
    projectId: 'frush-29e51',
    databaseURL: 'https://frush-29e51-default-rtdb.firebaseio.com',
    storageBucket: 'frush-29e51.firebasestorage.app',
    androidClientId:
        '792020357769-84l0irvq3ej12lp7mg47gehmqtdifu2e.apps.googleusercontent.com',
    iosClientId:
        '792020357769-c2cu8q8v2fjvnsi1ceqpqmjgp432a4qk.apps.googleusercontent.com',
    iosBundleId: 'com.sameats.customer.ios',
  );
}
